### ISSUE TITLE
Language Generation

### ISSUE THREAD

**Issue by Anas-Abdelhadi** [Can-Sahin/react-boilerplate-typescript#23]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Steps to reproduce
Try Adding a new language through the generator Command
`npm run generate language`
 
**Expected behavior**
The new language should be generated successfully. instead an error appears

**Screenshots**
![language_error](https://user-images.githubusercontent.com/44828864/65827907-ddc61580-e29d-11e9-8a6d-8479c1d1b582.png)

## Versions
4.1

**Comment by Can-Sahin** [comment]
Thanks. I never tried i8n before. `extract-intl` isnt working for now. I marked as TODO. I will fix it when I have time later. For now you can generate a language but cannot autofill messages with `extract-intl`
