### ISSUE TITLE
Babel Error: Unexpected Token

### ISSUE THREAD

**Issue by ashishkumar-compro** [Can-Sahin/react-boilerplate-typescript#25]
## Description
I am trying to use [draft-js-inline-toolbar-plugin](https://www.draft-js-plugins.com/plugin/inline-toolbar) inside react-boilerplate-typescript and I am getting the following error:

![image](https://user-images.githubusercontent.com/54092895/66564311-54f08900-eb7d-11e9-8203-22f25987dec4.png)

I have tried to use the same library in [react-boilerplate](https://github.com/react-boilerplate/react-boilerplate), and it's working fine.

## Steps to reproduce

Clone the following repo:

https://github.com/ashishkumar-compro/draft-js-inline-toolbar-plugin-react-boilerplate-typescript.git

Run the following commands:

1. npm install
2. npm start

**Expected behavior**
The Babel error should not come.

## Versions

- React-Boilerplate: 4.1
- Node/NPM: 10.16.3 / 6.9.0
- Browser: Chrome Version 77.0.3865.90

**Comment by Can-Sahin** [comment]
Can you delete these lines in `babel.config.js` file. I think unused babel typescript plugin is ruining something. It works with me. Can you verify that it works for you too ?

https://github.com/Can-Sahin/react-boilerplate-typescript/blob/05cb407d70d283889f525f2b1cf96c6603f66094/babel.config.js#L16-L21

**Comment by ashishkumar-compro** [comment]
Hi,

Thanks! It is working now, Also I tried to enable the isTSX option in @babel/plugin-transform-typescript and its working then also.

 [
      '@babel/plugin-transform-typescript',
      {
        isTSX: true,
        allowNamespaces: true,
      },
    ],

Which option do you recommend, completely removing the plugin or enabling the isTSX option?

**Comment by Can-Sahin** [comment]
Well I suggest you delete it. Babel typescript plugin isnt used. `ts-loader` does that work better in my opinion. So I kept that plugin as optional. Just remove it I'd say

**Comment by ashishkumar-compro** [comment]
ok thanx! 😄
