### ISSUE TITLE
[Feature Request] test runner for pull requests

### ISSUE THREAD

**Issue by GrayStrider** [Can-Sahin/react-boilerplate-typescript#33]
https://github.com/marketplace/travis-ci

**Comment by Can-Sahin** [comment]
There arent usually much pull requests but i will set travis up sometime soon. Thanks for all the pull requests. I will go over them.

**Comment by Can-Sahin** [comment]
i enabled travis-ci now and coveralls

https://travis-ci.org/Can-Sahin/react-boilerplate-typescript
https://coveralls.io/github/Can-Sahin/react-boilerplate-typescript
