### ISSUE TITLE
Update generator templates with latest changes

### ISSUE THREAD

**Issue by GrayStrider** [Can-Sahin/react-boilerplate-typescript#38]
We have 3 additional things to keen an eye on while introducing changes:
- internals/templates
- internal/generators
- tests

I suppose it's possible to eliminate the first 2 by adding additional tests for generators?
Thoughts?

**Comment by Can-Sahin** [comment]
Since this is a non-ts problem I will close it for now ok? The original boilerplate also does 1 and 2 manually. And honestly, after hooks I am not even using generators anymore :)
