### ISSUE TITLE
Replace tslint with eslint

### ISSUE THREAD

**Issue by GrayStrider** [Can-Sahin/react-boilerplate-typescript#39]
tslint is being superceded by eslint
https://eslint.org/blog/2019/01/future-typescript-eslint

- [ ] add support for eslint
- [ ] move all rules from tslint to eslint, keeping it as close as possible to upstream

**Comment by GrayStrider** [comment]
On a side note: I assume the sole purpose of `"allowJs": true`  for the time being is to enable some scripts from the upstream to work? I suppose it's fine to keep it on just in case someone will use it to transfer their project from js to ts, but maintaining a separate eslint config just for js seems superfluous.

**Comment by greyGroot** [comment]
i will do it

**Comment by aanari** [comment]
Any luck on this @greyGroot?

**Comment by greyGroot** [comment]
Sorry, i have to pass. Don't have free time at the moment. Sorry again.

**Comment by rajatkantinandi** [comment]
I want to work on this as I have set it up in a project recently that uses react-boilerplate-typescript.
If anyone else is not working on this is it OK if I take this up?

**Comment by rajatkantinandi** [comment]
Having an issue while trying to run `git pull upstream dev` while on dev branch locally.
It is trying to rebase & showing a bunch of conflicts although my local branch is up to date with dev branch of upstream.
I don't understand why is this trying to rebase.
Trying to follow the contribution guidelines but this is causing unexpected behavior.
I did a fork of the repo, cloned it locally, added upstream & checked out to dev branch.
Am I missing something?
Can someone help?

**Comment by Can-Sahin** [comment]
Merged in the `dev` branch with #61 thanks to @rajatkantinandi
