### ISSUE TITLE
Missing build:dll script in package.json

### ISSUE THREAD

**Issue by rzkhosroshahi** [Can-Sahin/react-boilerplate-typescript#5]
## Description
Hi,
in `postsetup` script run npm run build:dll`,  but seems it missed in the package.json file.

## Versions
- React-Boilerplate: 3.7.0

**Comment by Can-Sahin** [comment]
Hi. You are right. I forgot it there when switching to 3.7.0. Now build:dll is not needed. You can remove it from package.json. I am updating the master. After switching to 3.7.0, I didn't try `npm setup`.

**Comment by Can-Sahin** [comment]
I will check npm setup later in details. But if there are other issue please re-open. Thanks for the update !
