### ISSUE TITLE
Not working with IE11 and some older edge versions

### ISSUE THREAD

**Issue by TeaBough** [Can-Sahin/react-boilerplate-typescript#51]
The upstream boilerplate is working with IE11, but this typescript fork seems to not work with it. I get a blank screen with Script error. I tried to add browserslist in `package.json` without any success. I'll continue digging why it's not working, meanwhile if someone has an idea for a solution, I'm all ears :+1:

**Comment by GrayStrider** [comment]
Changing `"target"` in `tsconfig` to `"es5"` fixes the issue, submitting PR.
There are other errors in console as well, hot loader polyfil and some unhandled rejection, feel free to dig into it
