### ISSUE TITLE
Remove project fork status to properly display contributions

### ISSUE THREAD

**Issue by GrayStrider** [Can-Sahin/react-boilerplate-typescript#53]
Perhaps not neccesarily an issue with this particular project, but I would like to hear a commentary on that: [Why Commits to Forks on GitHub Don't Apply to Contributions](https://hisaac.net/2016/11/12/why-commits-to-forks-on-github-dont-count-toward-contributions/)

Quote: 
> Forks are designed as temporary places where you can work before merging your commits into the upstream repository. <...>
> If a fork becomes a different project from it’s upstream repository, and **will never have commits merged into the upstream repository**, then you can ask GitHub Support to detach the fork and turn it into a standalone repository. This will make the commits count towards your contributions.

In our case this is true; "fork" status simply points to the upstream repository and provides little utility function; how about we remove it? Then all activity of contributors will be displayed on their profiles correctly. 
This project is the first result in Google on "react boilerplate typescript" regardless:)
I've successfully removed fork status from my [other project](https://github.com/GrayStrider/react-boilerplate-typescript-1) by [asking support](mailto:developer@githubsupport.com) (and commits seem to have appeared in my activity log), so there shouldn't be any problems.

Of course we would still merge updates from upstream, but that doesn't require the project to have "fork" status.

**Comment by Can-Sahin** [comment]
I also thought about this too a while ago. And I actually was thinking of doing it and then there was a discussion on switching to typescript in the original boilerplate, so I didn't do that (to be able to merge this back)


https://github.com/react-boilerplate/react-boilerplate/pull/2648
https://github.com/react-boilerplate/react-boilerplate/issues/2768

have a look at these.

**Comment by GrayStrider** [comment]
I say we let this stay untill some concensus is achieved concerning the future of upstream.
