### ISSUE TITLE
Convert server to use typescript

### ISSUE THREAD

**Issue by jackdh** [Can-Sahin/react-boilerplate-typescript#57]
Current the main node server is still plain JS, can we update it to use typescript as well?

**Comment by Can-Sahin** [comment]
Its a development mode only thing. Starting the express server so I think its fine. Nobody ever touches it actually so I cant think of any reason for adding any types there. Plus it would add extra transpiling to every `npm start`. 

Do you have any reason adding types there would help developers ? If so we can consider

**Comment by jackdh** [comment]
No nothing in particular. 

I know for large applications alot of the time people would split out the front / back however for smaller applications it tends to be quicker to just package it all in one.

From there the reasons to have it our exactly the same as why we have typescript on the frontend :).

I'd be happy to work on a pull request if that would be helpful?

**Comment by Can-Sahin** [comment]
I didnt quite understand what you meant 😕How does packaging front and back as one relates to this boilerplate. Its front-end only static website (build folder only) 

I of course love types :) but when it comes to developing (writing the application code). Server here is %100 separated from anyones application code or is it not in your case ? Nobody makes changes in the server folder and types there are totally irrelevant for people. I'm bit skeptical adding another typescript transpilation here. It would compile everytime you run and almost 99% of those times people would wait for types to transpile they dont even care. Can you elaborate bit more your point of view :)

**Comment by ghost** [comment]
@jackdh 
This boilerplate only has frontend, no backend included.
The node server serves as HMR (hot module replacement) on dev environment and has nothing to do in production.

**Comment by jackdh** [comment]
@Can-Sahin @ericviston 

Not to worry, I guess I was looking to do something like:

https://github.com/TrillCyborg/fullstack

However as @ericviston  says if this is frontend only then it makes sense to leave the server as it is :)
