### ISSUE TITLE
development build is taking too long.

### ISSUE THREAD

**Issue by saeedjalalisj** [Can-Sahin/react-boilerplate-typescript#6]
**Is your feature request related to a problem? Please describe.**
When I start to run in development mode, build time is very long. For example `161674ms`.

**Comment by Can-Sahin** [comment]
So my case is generally around 15000ms. But I added `exclude: node_modules` rule to ts loader. Can you check if it speeds up. I guess it will. Just have a look at the commit a583287

If not can you re-open the issue please
