### ISSUE TITLE
Can't import png file

### ISSUE THREAD

**Issue by Surm4** [Can-Sahin/react-boilerplate-typescript#68]
## Description
Can't import img file (problem with webpack.base.babel.js) 
Error says: Expected `options.quality` to be of type `array` but received `string`

## Steps to reproduce
- clone boilerplate
- npm run setup
- npm run clean
- try import .png file 

**Expected behavior**
File should be imported

**Screenshots**
![Imgur](https://imgur.com/UStL1E7.png)

## Versions
- React-Boilerplate: 4.1
- Node/NPM: 12.6.1/6.13.4
- Browser: Chrome Canary 84.0.4104.0

## **Possible fix**
I think it will (works on my pc) work but I didnt run any coverage 
I changed quality property to this in the image
![Imgur](https://imgur.com/AhjzAjy.png)

**Comment by Can-Sahin** [comment]
Thanks for this. I didn't realize they changed it to an array. I'll fix in the `dev` branch
