### ISSUE TITLE
after run npm clean thrown some error 

### ISSUE THREAD

**Issue by saeedjalalisj** [Can-Sahin/react-boilerplate-typescript#7]
## Description
After clone and run setup and npm start every thing is working, but after run `npm run clean` I got some error:
```
✖ ｢atl｣: Checking finished with 3 errors
webpack built 3a0d1f697f3794a2671b in 8013ms
✖ ｢wdm｣: 
ERROR in ./app/reducers.ts
Module not found: Error: Can't resolve 'containers/App/reducer' in '/home/saeed/kamva/rbt-2/app'
 @ ./app/reducers.ts 4:0-51 9:12-25
 @ ./app/configureStore.ts
 @ ./app/app.tsx
 @ multi ./node_modules/react-app-polyfill/ie11.js webpack-hot-middleware/client?reload=true ./app/app.tsx

ERROR in [at-loader] ./app/types/index.d.ts:4:44 
    TS2307: Cannot find module 'containers/App/types'.

ERROR in [at-loader] ./app/types/index.d.ts:5:45 
    TS2307: Cannot find module 'containers/HomePage/types'.

ERROR in [at-loader] ./app/reducers.ts:9:27 
    TS2307: Cannot find module 'containers/App/reducer'.

```

## Steps to reproduce
1. run `npm run setup`
2. run `npm run clean`

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM:  10.11.0/6.4.1
- Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)
- Os: Linux ubuntu 18.04

**Comment by Can-Sahin** [comment]
Thanks for it. I fixed it with the commit just made -> 411b97d
After the merge for 3.7 version everything kinda messed a bit and couldn't have time to look into it until now.
