### ISSUE TITLE
Uncaught exception in promise: openSansObserver.load()

### ISSUE THREAD

**Issue by FrozenKiwi** [Can-Sahin/react-boilerplate-typescript#8]
Before opening a new issue, please take a moment to review our [**community guidelines**](https://github.com/react-boilerplate/react-boilerplate/blob/master/CONTRIBUTING.md) to make the contribution process easy and effective for everyone involved.

## Description
After a clean clone + clean + run, on app load we recieve the following exception:

Uncaught (in promise) A {family: "Open Sans", style: "normal", weight: "normal", stretch: "normal"}
Promise.then (async)
(anonymous) | @ | [app.tsx?f817:40](https://github.com/Can-Sahin/react-boilerplate-typescript/blob/master/app/app.tsx#L40)

## Steps to reproduce

clone full repo
npm run setup
npm run clean
npm start

: Navigate to homepage, see error in console

**Expected behavior**

Clean console.  NOTE: The base react-boilerplate did not have this error

**Screenshots**

## Versions

- React-Boilerplate: 3.7.0
- Node/NPM: 10.10.0
- Browser: Chrome 71

NOTE: This is my first TS project, so it could be something very simple, but as it's the first thing I see on run I figure it's worth creating an issue for

**Comment by FrozenKiwi** [comment]
Sorry - why was this issue closed?  Is the report not clear enough?

**Comment by Can-Sahin** [comment]
I fixed it with my commit 2ed8fe0

you can see the closing reason. Thanks for the report.

**Comment by FrozenKiwi** [comment]
Oops - I somehow read over the commit link!  Thanks for the response (and the repo in general, TS is as important to scale as anything else in RBP)
